name: consentimiento_informado
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  snack: ^2.0.0
  dio: ^5.4.3+1
  provider: ^6.1.2
  intl: ^0.19.0
  path_provider: ^2.1.3
  flutter_drawing_board: ^0.7.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
